services:
  # Backend API Service
  - type: web
    name: pollsvoting-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://cs350892_db_user:XzZwdok7uyxNsn3x@cluster0.g1u1e67.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        value: 0a72536b5889c03b70edc0cbde5184639ba2310c8211e48d08970e1725447421291d9a1ecb7bc21f0af84e8b13d52a9af5bd387109013d4031a189ffde1a03df
      - key: FRONTEND_URL
        value: https://pollsvoting-frontend.onrender.com

  # Frontend Static Site
  - type: web
    name: pollsvoting-frontend
    env: static
    region: singapore
    plan: free
    buildCommand: cd frontend && npm ci && npx vite build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://pollsvoting-backend-0etz.onrender.com/api
